title: Gradient of Me
author: Oleksandr Davyskyba
description: Hi there ğŸ–. I'm Alex ğŸ‡ºğŸ‡¦ â€” a passionate software engineer with a love for coding, technology, and continuous learning.
github_username:  zviryatko
theme: minima
minima:
  show_excerpts: true
  nav_pages:
    - about.md
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/zviryatko"
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/zviryatko/"
  skin: auto
  hide_site_feed_link: true
google_analytics: G-6G5LPB7WEB
plugins:
  - jekyll-seo-tag
  - jekyll-feed