theme: minima
title: zviryatko's blog
author: Oleksandr Davyskyba
description: Hi there ğŸ–. I'm developer from Ukraine ğŸ‡ºğŸ‡¦, and here my tiny personal blog.
github_username:  zviryatko
markdown: kramdown
